{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.fullname" . }}-secrets
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.secretValues.jwtSecret | quote }}
  postgres-password: {{ .Values.secrets.secretValues.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.secretValues.redisPassword | quote }}
  minio-password: {{ .Values.secrets.secretValues.minioPassword | quote }}
  meili-key: {{ .Values.secrets.secretValues.meiliKey | quote }}
{{- end }}
