apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.voicePort }}
      targetPort: voice
      protocol: TCP
      name: voice
    - port: {{ .Values.service.federationPort }}
      targetPort: federation
      protocol: TCP
      name: federation
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
